### ISSUE TITLE
Sonarqube does not show unit tests but shows unit tests coverage

### ISSUE THREAD

**Issue by brijeshdhakar** [Zetten/bazel-sonarqube#10]
When I run the sonarqube analysis on my java project, It generates the unit tests coverage but the Unit tests section is empty on sonarqube.

Test coverage is generated from the coverage report which was the result of following command
`bazel test //... --collect_code_coverage --combined_report=lcov --coverage_report_generator=@bazel_sonarqube//:sonarqube_coverage_generator`

**Comment by Zetten** [comment]
Bazel already emits Junit-style reports, so I think it would be sufficient to inject the property `sonar.junit.reportPaths=bazel-testlogs/**/test.xml`.

You could try this by appending `-Dsonar.junit.reportPaths=bazel-testlogs/**/test.xml` to the `bazel run :my_sonarqube_target` call. Or you should be able to create your own `sonar-project.properties.tpl` if you want to configure more properties.

I haven't actually tested this myself, so I'm curious to know if it works, or if I will have to create a Generic Execution Data aggregator.

**Comment by brijeshdhakar** [comment]
On using `Dsonar.junit.reportPaths` falg, it gives in the logs that sonar has parsed the test reports but it does not show the tests on sonarqube.

**Comment by Zetten** [comment]
I'm investigating this now, and it does seem more complex than I'd hoped. In particular, it seems that SonarQube has some more constraints on the report filenames, which Bazel does not follow:

```
Reports path contains no files matching TEST-.*.xml : /path/to/my_workspace/bazel-out/k8-fastbuild/bin/my_sonarqube_target.runfiles/my_workspace/bazel-testlogs/package/PackageTest
```

I'm working on extending the rules to support it.

**Comment by brijeshdhakar** [comment]
Yes sonarqube expects the reports to be in surefire-reports format. I tried this by giving the path of surefire-reports that I generated to test this.

**Comment by Zetten** [comment]
I've pushed support for collecting unit test reports. It seems to work in my local tests - please let me know if it works for you!

In your root BUILD file, export the test reports (same as for coverage):

```
filegroup(
    name = "test_reports",
    srcs = glob(["bazel-testlogs/**/test.xml"]),
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
```

In each `sonarqube` or `sq_project`, reference test sources, test targets (e.g. `java_test`), and the test reports:

```
sq_project(
  name = "my_sq",
  ...
  test_srcs = glob(["src/test/java/**/*.java"]),
  test_targets = [
    ":MyFirstTest",
    ":MySecondTest",
  ],
  test_reports = ["//:test_reports"],
)
```

**Comment by brijeshdhakar** [comment]
Yes, It works for me.
Thanks a lot.
