### ISSUE TITLE
got unexpected keyword arguments: test_srcs, test_targets, test_reports when execute "bazel run" command

### ISSUE THREAD

**Issue by dzdeping** [Zetten/bazel-sonarqube#12]
Hi ,@Zetten.
Luckily to see your code, and it's very helpful for our current work. But as i`m a fresher on both sonarqube and bazel, so I got some errors when i referring to your features.  Could you please help have a look ? thanks!
My command is:  
**bazel run //:sq -- -Dsonar.host.url=MY_URL -Dsonar.login=MY_ACCOUNT -Dsonar.password=MY_PASSWORD**
**Then got this error:**

_ERROR: Traceback (most recent call last):
        File "/opt/code/serp/bepcloudbazel/bepcloud/bepcloud-parent/bepcloud-common/BUILD", line 78, column 11, in <toplevel>
                sq_project(
        File "/root/.cache/bazel/_bazel_root/b522ef4008cbaf1fbce240d7f801c5b6/external/bazel_sonarqube/defs.bzl", line 160, column 5, in sq_project
                def sq_project(
**Error: sq_project() got unexpected keyword arguments: test_srcs, test_targets, test_reports**
ERROR: /opt/code/serp/bepcloudbazel/bepcloud/BUILD.bazel:28:10: Target '//bepcloud-parent/bepcloud-common:bepcloud_common_1_0_0_RELEASE' contains an error and its package is in error and referenced by '//:sq'
ERROR: Analysis of target '//:sq' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.324s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)_

**While my parent BUILD.bazel file is :**

_package(default_visibility = ["//visibility:public"],)

filegroup(
    name = "git",
    srcs = glob(
        [".git/**"],
        exclude = [".git/**/*[*"],  # gitk creates temp files with []
    ),
    tags = ["manual"],
)

filegroup(
    name = "coverage_report",
    srcs = ["bazel-out/_coverage/_coverage_report.dat"], # Created manually
    tags = ["manual"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_reports",
    srcs = glob(["bazel-testlogs/**/test.xml"]), # Created manually
    tags = ["manual"],
    visibility = ["//visibility:public"],
)

load("@bazel_sonarqube//:defs.bzl", "sonarqube")

sonarqube(
    name = "sq",
    project_key = "bepcloud-common-bazel:common",
    project_name = "bepcloud-common-bazel",
    srcs = glob(["src/main/java/**/*.java"]),
    targets = [
        "//bepcloud-parent/bepcloud-common:bepcloud_common_1_0_0_RELEASE"
    ],
    coverage_report = ":coverage_report",
    scm_info = [":git"],
    tags = ["manual"],
)_

**My componet BUILD file is:**

_load("@bazel_sonarqube//:defs.bzl", "sq_project")

sq_project(
    name = "bepcloud-common-component",
    project_key = "bepcloud-common:component",
    project_name = "bepcloud-commom :: Component",
    srcs = [
        "src/main/java/**/*.java",
    ],
    targets = [
       "bepcloud_common_1_0_0_RELEASE",
    ],
    test_srcs = ["src/test/java/com/huawei/bepcloud/validater/TestCompareValidater.java"],
    test_targets = [
        "TestCompareValidater.java",
    ],
    test_reports = ["//:test_reports"],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)_

**Comment by dzdeping** [comment]
FYI : I`m useing bazel version: 3.5.0,

**Comment by Zetten** [comment]
Hi @dzdeping, I think the issue might be to do with the version of this project you're using. The error indicates the `test_srcs`, `test_targets` and `test_reports` parameters are not found in the rules. They were all added in the latest commit (56537ff1cf4e6c28fba2b06e0f20d1f4e186645e).

Can you please check which revision of this repo you're using in your `WORKSPACE` file? If you're using a branch reference like `master`, I suggest changing it to the latest commit ID, in order to force bazel to download the specific thing you want.

When I eventually get around to making a proper release for this, I'll ensure the changes are documented better!

**Comment by dzdeping** [comment]
Hi @Zetten , thanks for your reply.  i have these contents in my WORKSPACE when i met **"Error: sq_project() got unexpected keyword arguments: test_srcs, test_targets, test_reports"** (i refereed the issue **#3**):
_http_archive(
    name = "bazel_sonarqube",
    sha256 = "336b9b9953257d927ba74ff9423f21b4d406be48dfcb7dc9ab21adedbc91709d",
    strip_prefix = "bazel-sonarqube-7b84f80f5d852cab94e8148cbf2255136078e466",
    urls = ["https://github.com/Zetten/bazel-sonarqube/archive/7b84f80f5d852cab94e8148cbf2255136078e466.zip"],
)
load("@bazel_sonarqube//:repositories.bzl", "bazel_sonarqube_repositories")
bazel_sonarqube_repositories()_

**Comment by Zetten** [comment]
Can you try replacing this with the below? Updating the url to end `56537ff....zip` should pull in the commit with the features you need.

```
http_archive(
    name = "bazel_sonarqube",
    sha256 = "e33f8222983b20cc4eb7d128db68bf83a63571d0b6e05b97bd3871b81f8fb9d9",
    strip_prefix = "bazel-sonarqube-56537ff1cf4e6c28fba2b06e0f20d1f4e186645e",
    urls = ["https://github.com/Zetten/bazel-sonarqube/archive/56537ff1cf4e6c28fba2b06e0f20d1f4e186645e.zip"],
)

load("@bazel_sonarqube//:repositories.bzl", "bazel_sonarqube_repositories")

bazel_sonarqube_repositories(
    sonar_scanner_cli_sha256 = "a271a933d14da6e8705d58996d30afd0b4afc93c0bfe957eb377bed808c4fa89",
    sonar_scanner_cli_version = "4.5.0.2216",
)
```

**Comment by dzdeping** [comment]
Thanks !  yes, i have already update the WORKSPACE by refered to:  https://github.com/cgi-eoss/libeopp   ,  those error disappeared, but got another error.
and created an issue: https://github.com/cgi-eoss/libeopp/issues/1

**Comment by Zetten** [comment]
I see in cgi-eoss/libeopp#1 that you have already updated the commit, and now are having troubles with generating coverage!

I saw that the test result was cached and didn't actually execute. Can you please try running `bazel coverage //... --nocache_test_results` and see if we get anything different?

**Comment by dzdeping** [comment]
Hi, @Zetten . i run command: 
**bazel clean**
**bazel coverage //... --nocache_test_results**
And get outputs as : 

_INFO: Using default value for --instrumentation_filter: "//bepcloud-parent/bepcloud-common[/:]".
INFO: Override the above default with --instrumentation_filter
INFO: Analyzed 6 targets (33 packages loaded, 230 targets configured).
INFO: Found 5 targets and 1 test target...
INFO: LCOV coverage report is located at /root/.cache/bazel/_bazel_root/b522ef4008cbaf1fbce240d7f801c5b6/execroot/__main__/bazel-out/_coverage/_coverage_report.dat
 and execpath is bazel-out/_coverage/_coverage_report.dat
INFO: From CoverageReport _coverage/_coverage_report.dat:
Jan 21, 2021 5:47:44 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator getTracefiles
INFO: Found 1 tracefiles.
Jan 21, 2021 5:47:44 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator parseFiles
SEVERE: Parsing file bazel-out/k8-fastbuild/testlogs/bepcloud-parent/bepcloud-common/subarrytest/coverage.dat
Jan 21, 2021 5:47:44 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator getGcovInfoFiles
INFO: No gcov info file found.
Jan 21, 2021 5:47:44 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator getProfdataFileOrNull
INFO: No .profdata file found.
Jan 21, 2021 5:47:44 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator main
WARNING: There was no coverage found.
ERROR: <builtin>: output '_coverage/_coverage_report.dat' was not created
ERROR: <builtin>: not all outputs were created or valid
INFO: Elapsed time: 3.378s, Critical Path: 3.19s
INFO: 18 processes: 13 linux-sandbox, 5 worker.
FAILED: Build did NOT complete successfully
//bepcloud-parent/bepcloud-common:subarrytest                            PASSED in 0.7s

Executed 1 out of 1 test: 1 test passes.
All tests passed but there were other errors during the build.
FAILED: Build did NOT complete successfully_

**it seems  no difference except the timestamp.**

**Comment by Zetten** [comment]
When I compare to the good build of another project, the key difference in your log is:

```
 WARNING: There was no coverage found.
```

So let's try to find why you have no `coverage.dat` file for your tests - I think this is the root problem, and it's not specifically a bazel-sonarqube issue.

When I do `bazel coverage //file:FileMetasTest`, and then inspect the `bazel-testlogs` directory for that test, I can see these outputs:

```
$ ls -1 bazel-testlogs/file/FileMetasTest/
baseline_coverage.dat
coverage.dat
test.cache_status
test.log
test.outputs
test.outputs_manifest
test.raw_splitlogs
test.xml
```

Can you see anything similar? In your case I guess the directory is `bazel-testlogs/bepcloud-parent/bepcloud-common/subarrytest`.

Unfortunately Bazel's coverage support is quite complex and I don't fully understand the internals. You might have more luck asking the general Bazel community via the bazel-discuss mailing list or Slack.

**Comment by dzdeping** [comment]
@Zetten Many thanks for your help!  I'll analyze the problem further. When I find the answer, it'll be updated here.
By the way， what in my bazel-testlogs/bepcloud-parent/bepcloud-common/subarrytest are:

-r-xr-xr-x 1 root root   218 Jan 21 17:53 ./baseline_coverage.dat*
-r-xr-xr-x 1 root root     0 Jan 21 17:53 ./coverage.dat*
-r-xr-xr-x 1 root root   193 Jan 21 17:53 ./test.cache_status*
-r-xr-xr-x 1 root root 10314 Jan 21 17:53 ./test.log*
-rw-r--r-- 1 root root   525 Jan 21 17:53 ./test.xml

./test.outputs:
total 8
drwxr-xr-x 2 root root 4096 Jan 21 19:07 ./
drwxr-xr-x 5 root root 4096 Jan 21 17:53 ../

./test.outputs_manifest:
total 8
drwxr-xr-x 2 root root 4096 Jan 21 19:07 ./
drwxr-xr-x 5 root root 4096 Jan 21 17:53 ../

./test.raw_splitlogs:
total 8
drwxr-xr-x 2 root root 4096 Jan 21 19:07 ./
drwxr-xr-x 5 root root 4096 Jan 21 17:53 ../

**Comment by dzdeping** [comment]
Hi, @Zetten 
i got another error, and be confused with value of the attribute "test_targets", what should i set for the attribute ?
`**run command :** **bazel coverage //bepcloud_parent/bepcloud_common:sq_subtest**`

**get error as :**
`ERROR: /opt/code/serp_sonar_test/bepcloudbazel/bepcloud/bepcloud_parent/bepcloud_common/BUILD:85:11: in _sq_project rule //bepcloud_parent/bepcloud_common:sq_subtest:
Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ef23feb022b492d353b857069ef82962/external/bazel_sonarqube/defs.bzl", line 226, column 53, in _sq_project_impl
                local_runfiles = _build_sonar_project_properties(ctx, ctx.outputs.sq_properties)
        File "/root/.cache/bazel/_bazel_root/ef23feb022b492d353b857069ef82962/external/bazel_sonarqube/defs.bzl", line 37, column 110, in _build_sonar_project_properties
                bazel_test_report = [t for t in ctx.files.test_reports if t.short_path == bazel_test_report_path][0] or fail("Expected Bazel test report for %s with path %s" % (test_target, bazel_test_report_path))
Error: index out of range (index is 0, but sequence has 0 elements)
ERROR: Analysis of target '//bepcloud_parent/bepcloud_common:sq_subtest' failed; build aborted: Analysis of target '//bepcloud_parent/bepcloud_common:sq_subtest' failed
INFO: Elapsed time: 0.072s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 451 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 451 targets configured)`

**My parent BUILD.bazel file**
`load("@bazel_sonarqube//:defs.bzl", "sonarqube")
filegroup(
    name = "git",
    srcs = glob(
        [".git/**"],
        exclude = [".git/**/*[*"],  # gitk creates temp files with []
    ),
    tags = ["manual"],
)
filegroup(
    name = "coverage_report",
    srcs = ["bazel-out/_coverage/_coverage_report.dat"],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_reports",
    srcs = glob(["bazel-testlogs/**/test.xml"]),
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
sonarqube(
    name = "sq",
    project_key = "bepcloud:bepcloud_common",
    project_name = "bepcloud_common_bazel",
    modules = {
        "//bepcloud_parent/bepcloud_common:sq_subtest":"bepcloud_parent/bepcloud_common",
    },
    coverage_report = ":coverage_report",
    scm_info = [":git"],
    tags = ["manual"],
)
`
**My child BUILD file:**
`java_library(
   name = "source_java",
   srcs = ["src/main/java/com/it/bepcloud/validater/SubArray.java"],
   visibility = ["//visibility:public"],
)
load("@bazel_sonarqube//:defs.bzl", "sq_project")

sq_project(
   name = "sq_subtest",
   project_key = "com.it.bepcloud:sq_subtest",
   project_name = "bepcloud_common :: sq_subtest",
   srcs = [
        "//bepcloud_parent/bepcloud_common:bepcloud_common_1_0_0_RELEASE",
   ],
   targets = [
        "@maven//:junit_junit",
   ],
   test_srcs = [
        "src/main/java/com/it/bepcloud/validater/SubArrayTest.java",
   ],
   test_targets = [
        "//bepcloud_parent/bepcloud_common:source_java",
   ],
   test_reports = ["//:test_reports"],
   tags = ["manual"],
   visibility = ["//visibility:public"],
)
`

**Comment by Zetten** [comment]
Hi @dzdeping,

The `test_targets` attribute should be a list of the `java_test` targets which are relevant to the module. If you don't have any tests in the project (i.e. in your child BUILD file) you can simply omit the `test_srcs`, `test_targets` and `test_reports` parameters.

I'm working on expanding the documentation and creating a simpler example project which will hopefully help!

**Comment by Zetten** [comment]
Please see the example project in https://github.com/Zetten/bazel-sonarqube/blob/master/examples/java - it should be a bit easier to understand and copy for your analysis.

**Comment by dzdeping** [comment]
Hi, @Zetten   **much thanks** for your update, it do helpfully , and maybe i found where is the problem:
Our code need openjdk8 to build, so my **.bazelrc** file was created as :

**build --define=ABSOLUTE_JAVABASE=/opt/buildtools/adoptopenjdk-8u242b08/jdk8u242-b08
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
coverage --collect_code_coverage
coverage --combined_report=lcov
coverage --coverage_report_generator=@bazel_sonarqube//:sonarqube_coverage_generator**

when i use my .bazelrc file to run your example project, the **bazel-out/_coverage/_coverage_report.dat** file be a empty file.
 It could be because "**Bazel is configured to use a default OpenJDK 11 for building and testing JVM-based projects.**" (refer to https://docs.bazel.build/versions/3.6.0/bazel-and-java.html#configuring-the-jdk ).

i think your function "bazel-sonarqube" maybe use OpenJDK 11 too to generate coverage. 
So ,when i switch to another JDK, i can build successfully, but i can not generate a good **_coverage_report.dat** file.

But from now, i still struggling to solve this JDK problem

**Comment by Zetten** [comment]
So it's a little bit confusing. For a Bazel project with Java code, there are actually multiple JDK/JVMs involved: Bazel itself (an embedded/bundled OpenJDK 11) plus the tooling (i.e. the JDK to build and run your Java code). It's further complicated by the fact that Bazel supports a separate "host" toolchain, so you can compile your build tooling separately from your project code.

Unless you configure it differently, Bazel will set up an OpenJDK 11 toolchain for your builds. So yes, the example project will be using an automatically-downloaded Java 11 toolchain.

However you _have_ configured it specifically to use your local JDK. I have other builds which use different JVMs, so I didn't think this was a problem.

But I've done some more testing now, with different flags for the Java toolchain. Results are interesting, and apparently not due to the JDK version but rather the specific bazel toolchain arguments used. The problem seems to be with `toolchain_vanilla`.

```
# defaults, i.e. Bazel's automatically-determined OpenJDK 11
```
:heavy_check_mark: 

```
# OpenJDK 11 specified by ABSOLUTE_JAVABASE with toolchain_vanilla
build --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-11-openjdk
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
```
:x: 

```
# OpenJDK 11 specified by ABSOLUTE_JAVABASE with toolchain_java11
build --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-11-openjdk
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
```
:heavy_check_mark:

```
# OpenJDK 11 specified by local_jdk, i.e. using $JAVA_HOME in the environment
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build --javabase=@local_jdk//:jdk
build --host_javabase=@local_jdk//:jdk
```
:heavy_check_mark:

```
# OpenJDK 8 specified by ABSOLUTE_JAVABASE
build --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-8-openjdk
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
```
:x:

```
# OpenJDK 11 specified by ABSOLUTE_JAVABASE with toolchain_hostjdk8
build --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-8-openjdk
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
```
:heavy_check_mark:

```
# OpenJDK 8 specified by local_jdk, i.e. using $JAVA_HOME in the environment
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --javabase=@local_jdk//:jdk
build --host_javabase=@local_jdk//:jdk
```
:heavy_check_mark:

So I think all you need to do is change your `toolchain_vanilla` to `toolchain_hostjdk8`. I'm not sure what the purpose of `vanilla` is but I suspect the toolchain is not actually adding any parameters for instrumenting the Java code for coverage collection.

**Comment by dzdeping** [comment]
@Zetten  Yes  yes  yes .  Your suggestion is correct. i changed to `toolchain_hostjdk8` and then add some maven dependency for every individual component , it finally success to run `bazel coverage`  and `bazel run //:sq` .

**Thank you so much for your help**. ☺

**Comment by Zetten** [comment]
Fantastic! It took a while but I'm glad we got there in the end!
