### ISSUE TITLE
provide a release

### ISSUE THREAD

**Issue by DanielK2013** [Zetten/bazel-sonarqube#15]
Can you provide a release to be consumed using http_archive?

**Comment by ignaciogonzalezsomoza** [comment]
Good morning, we are in the same situation, currently we used:
 http_archive(
    name = "bazel_sonarqube",
    sha256 = "e33f8222983b20cc4eb7d128db68bf83a63571d0b6e05b97bd3871b81f8fb9d9",
    strip_prefix = "bazel-sonarqube-56537ff1cf4e6c28fba2b06e0f20d1f4e186645e",
    urls = ["https://github.com/Zetten/bazel-sonarqube/archive/56537ff1cf4e6c28fba2b06e0f20d1f4e186645e.zip"],
)
Which seems to be the one recommended in the author's comments, but suddenly this sha seems to have changed. 
We join the previous request.
Thank you.

**Comment by adincebic** [comment]
@DanielK2013 @ignaciogonzalezsomoza I worked with @Zetten to address this. We also now support bzlmod. Please check github releases for this repo.

**Comment by adincebic** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/2121
