### ISSUE TITLE
Sonar project dashboard is empty after using the bazel run command

### ISSUE THREAD

**Issue by sriharshaganti** [Zetten/bazel-sonarqube#8]
Steps to reproduce
1. Configure the bazel-sonar plugin in th WORKSPACE file
2. Create the target
3. generate the coverage.dat file from the target
4. Use the command 
`bazel run //:sonar_coverage -- -Dsonar.host.url=<host> -Dsonar.login=<token>`
Expected:
Project created in sonar dashboard with analysis results
Actual:
Project is created but the analysis is empty

**Comment by Zetten** [comment]
It sounds like there's an issue with the Sonar Scanner config. Can you check the logs from the `bazel run` command?

At first thought, maybe you accidentally left out the `srcs` attribute on the `sonarqube`/`sq_project` targets?

**Comment by sriharshaganti** [comment]
I figured out the issue. Thanks. Have few doubts
1. srcs attribute: This will take the filegroup target of the main java files. i.e. file group target may contain glob of (*.java) files
2. targets attribute: I used output jar of java_binary rule and all the dependency target for this value. Though the sonarqube is working I wanted to know what is the right value to provide to this attribute
3. sq_project: Can I use sq_project rule for multiple modules(projects) in my repo(mono repo - contains multiple services) and  use it as a srcs in sonarqube rule. If so, will the sonarqube server create multiple projects according to the sq_project rule ?

**Comment by Zetten** [comment]
Great!

I admit the documentation needs a bit of work. To answer your questions:

1. The `srcs` attribute is a list of filegroup targets (or the files themselves) to be passed to the Sonar Scanner as the list of sources.
2. The `targets` attribute is the list of binary targets compiled from those sources, e.g. the `java_library` targets. Obviously not all languages will have this, but the Sonar Scanner output should make it clear if there's a problem.
3. You can compose multiple modules into a single SonarQube project by using the `sq_project` rule in the modules, and the `sonarqube` rule at the top level. They're mostly identical, but the `sonarqube` rule has an additional attribute to reference the `sq_project` targets and their path relative to the `sonarqube` rule. So for `sonarqube` at the root of the workspace, and a module (with `sq_project`) in the package `path/to/component`, use it like so:
    ```
    modules = {
        "//path/to/component:sq_mycomponent": "path/to/component",
    },
   ````

It's lacking polish, but the essential aim in these rules is to do two things:
1. Collect as runfiles all the file inputs (sources and binaries) required for a Sonar Scanner analysis.
2. Emit a valid `sonar-project.properties` with valid [analysis parameters](https://docs.sonarqube.org/latest/analysis/analysis-parameters/) and launch the Sonar Scanner in a context with the files from (1).

**Comment by sriharshaganti** [comment]
Thanks !!!
