### ISSUE TITLE
Issues while creating test coverage report

### ISSUE THREAD

**Issue by brijeshdhakar** [Zetten/bazel-sonarqube#9]
when i try to run the command to generate test coverage
`bazel test //... --collect_code_coverage \
  --combined_report=lcov \
  --coverage_report_generator=@bazel_sonarqube//:sonarqube_coverage_generator`

It fails with the following error,

Aug 19, 2020 2:10:50 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator getGcovInfoFiles
INFO: No gcov info file found.
Aug 19, 2020 2:10:50 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator getProfdataFileOrNull
INFO: No .profdata file found.
Aug 19, 2020 2:10:50 PM com.google.devtools.coverageoutputgenerator.SonarQubeCoverageGenerator main
WARNING: There was no coverage found.
ERROR: output '_coverage/_coverage_report.dat' was not created
ERROR: not all outputs were created or valid
FAILED: Build did NOT complete successfully
//11-commons-test:CategoryTimeoutRuleTest                                PASSED in 3.5s
//11-commons-test:ConcurrentTest                                         PASSED in 2.5s
//11-commons-test:ExtendsCategoryEnforcerTest                            PASSED in 2.3s
//11-commons-test:FakeClockTest                                          PASSED in 3.2s
//11-commons-test:OwnerMetadataTest                                      PASSED in 2.6s
//11-commons-test:ScmSecretTest                                          PASSED in 3.1s

Executed 6 out of 6 tests: 6 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
All tests passed but there were other errors during the build.
FAILED: Build did NOT complete successfully

**Comment by Zetten** [comment]
Can you try to collect coverage without the report generator? E.g. `bazel coverage //...` with no arguments.

If it reports `coverage.dat` files, ensure that they contain valid coverage data, like so:

```
$ head -n20 bazel-testlogs/file/FileMetasTest/coverage.dat
SF:file/src/main/java/com/cgi/eoss/eopp/file/EoppFileException.java
FN:7,com/cgi/eoss/eopp/file/EoppFileException::<init> (Ljava/io/IOException;)V
FNDA:1,com/cgi/eoss/eopp/file/EoppFileException::<init> (Ljava/io/IOException;)V
FNF:1
FNH:1
DA:7,3
DA:8,1
LH:2
LF:2
end_of_record
SF:file/src/main/java/com/cgi/eoss/eopp/file/FileMetas.java
FN:32,com/cgi/eoss/eopp/file/FileMetas::<clinit> ()V
FN:184,com/cgi/eoss/eopp/file/FileMetas::checksum (Lcom/google/common/hash/HashCode;Lcom/google/common/hash/HashFunction;)Ljava/lang/String;
FN:166,com/cgi/eoss/eopp/file/FileMetas::checksum (Lcom/google/common/io/ByteSource;)Ljava/lang/String;
FN:175,com/cgi/eoss/eopp/file/FileMetas::checksum (Lcom/google/common/io/ByteSource;Lcom/google/common/hash/HashFunction;)Ljava/lang/String;
FN:143,com/cgi/eoss/eopp/file/FileMetas::fromBase64 (Ljava/lang/String;)Lcom/cgi/eoss/eopp/file/FileMeta;
FN:56,com/cgi/eoss/eopp/file/FileMetas::get (Ljava/nio/file/Path;)Lcom/cgi/eoss/eopp/file/FileMeta;
FN:70,com/cgi/eoss/eopp/file/FileMetas::get (Ljava/nio/file/Path;Lcom/google/common/hash/HashFunction;)Lcom/cgi/eoss/eopp/file/FileMeta;
FN:101,com/cgi/eoss/eopp/file/FileMetas::get (Ljava/nio/file/Path;Lcom/google/common/hash/HashFunction;Ljava/util/Map;Z)Lcom/cgi/eoss/eopp/file/FileMeta;
FN:84,com/cgi/eoss/eopp/file/FileMetas::get (Ljava/nio/file/Path;Ljava/util/Map;)Lcom/cgi/eoss/eopp/file/FileMeta;
```

If that looks good, we can take a closer look at the report aggregator.

**Comment by brijeshdhakar** [comment]
I have .bazelrc with the following content

build --define=ABSOLUTE_JAVABASE=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla
build --java_header_compilation=false

Running `bazel coverage //...` generates empty coverage.dt files


But if i remove everything from `.bazelrc` and run the same command then coverage.dat files are generated

**Comment by Zetten** [comment]
Great!

It seems that Bazel coverage is tricky to get right; I should perhaps add some troubleshooting tips to this repo's readme.
